{"name": "Actualizar informacion del perfil", "status": "broken", "statusDetails": {"message": "TypeError: update_profile() got an unexpected keyword argument 'id'\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n"}, "steps": [{"name": "Given que exista un usuario con ID 1", "status": "passed", "start": 1715894652029, "stop": 1715894652605}, {"name": "When se envia una solicitud para actualizar la informacion del perfil con id 1, con datos aleatorios", "status": "broken", "statusDetails": {"message": "TypeError: update_profile() got an unexpected keyword argument 'id'\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n"}, "start": 1715894652606, "stop": 1715894652607}, {"name": "Then se recibe una respuesta exitosa despues de actualizar el perfil", "status": "skipped", "start": 1715894652609, "stop": 1715894652609}], "start": 1715894652028, "stop": 1715894652609, "uuid": "943c5981-5870-484c-aa57-50af8d34f555", "historyId": "b3ca619ec2d09ee5c2d100a7db600914", "fullName": "Gestión de Perfiles: Actualizar informacion del perfil", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gestión de Perfiles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}