{"name": "Actualizar informacion del perfil", "status": "broken", "statusDetails": {"message": "TypeError: update_profile() got an unexpected keyword argument 'id'\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n"}, "steps": [{"name": "Given que exista un usuario con ID 1", "status": "passed", "start": 1715894540246, "stop": 1715894540339}, {"name": "When se envia una solicitud para actualizar la informacion del perfil con id 1, con datos aleatorios", "status": "broken", "statusDetails": {"message": "TypeError: update_profile() got an unexpected keyword argument 'id'\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n"}, "start": 1715894540340, "stop": 1715894540341}, {"name": "Then se recibe una respuesta exitosa despues de actualizar el perfil", "status": "skipped", "start": 1715894540343, "stop": 1715894540343}], "start": 1715894540244, "stop": 1715894540343, "uuid": "dad7f0b1-7624-4057-8015-e596e86b8bd6", "historyId": "b3ca619ec2d09ee5c2d100a7db600914", "fullName": "Gestión de Perfiles: Actualizar informacion del perfil", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gestión de Perfiles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}